### ISSUE TITLE
IMAP auth not possible, IMAP service down?

### ISSUE THREAD

**Issue by bluepuma77** [sb-minimal/docker-ubuntu-open-exchange-imap#1]
I just tried the docker image and accessed the web page according to https://registry.hub.docker.com/u/sbminimal/docker-ubuntu-open-exchange-im/ 
But login is not possible with user oxadminmaster, seems there is no IMAP service running on port 143 inside the docker container.

```
2015-04-13T15:33:37,241+0000 INFO  [OXWorker-0000025] com.openexchange.authentication.imap.impl.IMAPAuthentication.handleLoginInfo(IMAPAuthentication.java:474)
Messaging error on host localhost:143 for user oxadminmaster@defaultcontext
 com.openexchange.ajax.action=login
 com.openexchange.ajax.module=login
 com.openexchange.grizzly.queryString=<none>
 com.openexchange.grizzly.remoteAddress=x.x.x.x
 com.openexchange.grizzly.remotePort=48661
 com.openexchange.grizzly.requestURI=/ajax/login
 com.openexchange.grizzly.serverName=localhost
 com.openexchange.grizzly.servletPath=/ajax/login
 com.openexchange.grizzly.threadName=OXWorker-0000025
 com.openexchange.grizzly.userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
 com.openexchange.login.authId=xyz123
 com.openexchange.login.client=open-xchange-appsuite
 com.openexchange.login.clientIp=x.x.x.x
 com.openexchange.login.login=oxadminmaster
 com.openexchange.login.userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
 com.openexchange.login.version=7.6.2-12
 com.openexchange.request.trackingId=xyz123
com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 143; timeout 5000
    at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:865)
    at javax.mail.Service.connect(Service.java:364)
    at com.openexchange.authentication.imap.impl.IMAPAuthentication.handleLoginInfo(IMAPAuthentication.java:446)
    at com.openexchange.authentication.service.Authentication.login(Authentication.java:89)
```

**Comment by sb-minimal** [comment]
This is correct and intentional.

The image does _not_ provide a own imap server. It is ment to be used with existing imap infrastructure.
(Otherwise, if you really want to manage users by hand / without existing infrastructure, you could use the docker-ubuntu-open-exchange image. This uses a local user database and connects to the external imap server only to read mail).

HINT:
Edit /opt/open-xchange/etc/imapauth.properties inside the image to specify the imap server to use.
IMAP_SERVER=your-imap-server-here

So, to clarify: this image is not ment to be a full blown smpt+imap mailserver but rather a convenient way to add open-exchange to a existing mailserver infrastructure.

Let me know if you need any more details on how to adapt the shipped config.
